[profile.default]
src = "contracts"
out = "out"
libs = ["node_modules", "lib"]
remappings = [
    "@openzeppelin/=node_modules/@openzeppelin/",
]
solc = "0.8.19"

[rpc_endpoints]
localhost = "http://localhost:8545"
